DROP TABLE IF EXISTS test;
 
CREATE TABLE test (
  id INT(11) AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  career VARCHAR(250) DEFAULT NULL
);

